name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: configure
      run: ./configure

    - name: Install dependencies
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck

    - name: Create Release
      if: success() # Only create a release if the previous steps were successful
      uses: softprops/action-gh-release@v1
      with:
        files: |
          path/to/your-compiled-artifact
        token: ${{ secrets.GITHUB_TOKEN }} # This token is provided by GitHub Actions
